# Generated by Django 5.0.4 on 2024-07-05 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('address', models.TextField(default='Unknown Address')),
                ('parent_tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.team')),
            ],
        ),
    ]
