# Generated by Django 5.0.4 on 2024-07-05 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
