# Generated by Django 5.0.4 on 2024-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_team_address_alter_team_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.CharField(default='Gasanze', max_length=50),
        ),
    ]
