# Generated by Django 5.0.4 on 2024-07-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_team_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
