# Generated by Django 5.0.4 on 2024-07-13 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='HandballMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Karate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='MinFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='VolleballMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(default='Gasanze', max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_tel', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
