# Generated by Django 5.0.4 on 2024-07-15 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_basketball_handballmember_karate_minfoot_tradition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vally_Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.volleballmember')),
            ],
        ),
    ]
